### PR TITLE
Shortcode display

### LINKED ISSUE #13: Add shortcode identifier for pasting in the post/pages
In https://github.com/ClassicPress-research/classic-code-snippets/pull/11#pullrequestreview-556030216, there is a request that translates into a new feature.

A need to have a shortcode that can be copied and pasted from the shortcode edit page into the reference pages/posts to make it easier for one to identify the code snippet they are cross-referencing.

### PR DESCRIPTION
**Pull request by bahiirwa**
Closes #13 

Image shows the shortcode to paste via the individual posts
Screenshot 2020-12-22 at 17 32 33

Image shows the shortcode to paste via post type columns
Screenshot 2020-12-22 at 17 32 52

### CODE REVIEW

**Comment by ghost** [comment]
I have just tested this and it works well. But where you have "Snippet to paste in post/page" shouldn't that be "Shortcode to paste in post/page"?

**Comment by bahiirwa** [comment]
I struggled a bit with this. English is my second language. Please advise @timbocode

**Comment by ghost** [comment]
Or it could say "Insert snippet in post/page using..."

**Comment by bahiirwa** [comment]
That makes sense even to me. I will work on it.

**Comment by bahiirwa** [comment]
This is ready for review after that change request.

**Comment by ghost** [comment]
Looking at it again, why not just use the heading "Shortcode". I don't feel there is any need to explain to people what a shortcode is for. My reasoning is that a longer heading makes the input box smaller, and I think the code box should be as big as possible.

**Comment by bahiirwa** [comment]
> Looking at it again, why not just use the heading "Shortcode". I don't feel there is any need to explain to people what a shortcode is for. My reasoning is that a longer heading makes the input box smaller, and I think the code box should be as big as possible.

I think it helps to make things easy for one to figure out the use. The word **shortcode** standing alone might be confusing.
In the PR #11, the goal is to have the labels and inputs in block structure so the length might not matter. If this gets merged first.

**Comment by ghost** [comment]
OK. We'll go with the longer heading. I have tested it on a site and it works for me so will approve.

**Comment by ghost** [comment]
Ah. OK We need to wait for @timbocode .

**Review by timbocode — APPROVED** [review]
LGTM

**Pull request merged**
