### PR TITLE
Fix docs & new screenshots

### LINKED ISSUE #17: Wrong code snippet shortcode examples
There are different examples shown on the plugin page and the code snippet list page.

image1

image2

### PR DESCRIPTION
**Pull request by bahiirwa**
This PR closes #17.

I does the fixes mentioned in https://github.com/ClassicPress-research/classic-code-snippets/issues/17#issuecomment-753786557

- [x] Fix docs
- [x] Add new screenshots
- [x] Fix whatever code generates the shortcode column on the post listing page.
- [x] Fix the text in the plugin description.

### CODE REVIEW

**Comment by ghost** [comment]
Have you renamed the CPT?

**Comment by bahiirwa** [comment]
> Have you renamed the CPT?

No, I haven't in this PR. The CPT remains as this `ccs_code_snippet` consistent with the text domain `ccs-code-snippets`.

Should we also rename this?

**Comment by ghost** [comment]
No, please. I just did a big import of all the code snippets into the CC site using that CPT.

Just testing now and it all looks good.

**Comment by bahiirwa** [comment]
> No, please. I just did a big import of all the code snippets into the CC site using that CPT.

My thoughts exactly. There a no breaking changes from the last PR #11 merged. Just documentation stuff and internationalization.

**Comment by ghost** [comment]
Nope, still missed one:

ccs

**Comment by ghost** [comment]
Line 229

**Comment by bahiirwa** [comment]
Quick catch fixed.

**Comment by ghost** [comment]
OK. That looks good.

But what has deleting form.php got to do with this PR?

**Review by ghost — APPROVED** [review]
Tested and all working well.

**Review by timbocode — APPROVED** [review]
Fixed conflict in `classic-code-snippets.php`. All good to go now.

**Comment by bahiirwa** [comment]
There is a little change in the ccs_snippet with “s” that’s going to bring some issues if someone copies from the admin listing

**Comment by timbocode** [comment]
Sorry @bahiirwa, I don't quite follow. Which change do you mean...and what admin listing?

Just to confirm, the shortcode is still `ccs_snippet` , right?

**Comment by ghost** [comment]
Yes, looks we lost one of the changes.

snippet

**Comment by bahiirwa** [comment]
@timbocode Alan gets its right with the screenshot. Fixing this would close #21

**Pull request merged**
