### PR TITLE
Rename

### LINKED ISSUE #7: Rename main file
The main file for this plugin is currently `sc-display-code.php` but I think this should be changed to `classic-code-snippets.php` in accordance with usual naming conventions.

### LINKED ISSUE #8: Replace function/variable prefix with ccs
Many functions and variables are currently prefixed with `sc` or `sc_my`. It would be better to prefix these with `ccs`.

### PR DESCRIPTION
**Pull request by bahiirwa**
This PR seeks to Close #8.

And closes #7 .

### Changes introduced

- Rename the prefix to `ccs_`
- i18n: Add new plugin text domain with new prefix `ccs-`
- Credits and Rename plugin

### CODE REVIEW

**Comment by bahiirwa** [comment]
Renaming the main file makes it hard to review this. We shall make a separate PR when this review is done.

**Comment by timbocode** [comment]
Also closes #7

**Comment by bahiirwa** [comment]
Let me resolve the issues.

**Review by timbocode — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
