### PR TITLE
Add Update Manager file

### LINKED ISSUE #3: Add updater to plugin
We need to consider adding an updater file to the plugin so that it is updatable on release here. Codepotent's plugin could do well.

### PR DESCRIPTION
**Pull request by ghost**
Update file has been added to a new directory called "includes". A line has been added to the main php file to call the Update Manager file on loading.

**NB. For now, the updates are being managed from the Classic Commerce website.**

To test...

1, Upload changed files to a test site.
2. Edit the main php file to make it a version below 1.0.0
3. Check for updates in backend - should show up as needing an update.
4. Proceed with update.

Closes #3

### CODE REVIEW

**Review by bahiirwa — APPROVED** [review]
LGTM.

**Review by timbocode — CHANGES_REQUESTED** [review]
1. The main plugin file needs to be renamed `classic-code-snippets.php` from the current `sc-display-code.php`. 

2. Might as well start as we mean to go on. Can you change the `UPDATE_SERVER` constant to `https://officialplugins.classicpress.net/`. I've set up an endpoint there but it needs the main file to be renamed first.

Otherwise, looks good!

**Comment by bahiirwa** [comment]
For changes request @timbocode, the filename `sc-display-code.php` will be changed in PR #11. This PR was a one task concern.

**Comment by ghost** [comment]
Endpoint has been changed in new commit.

**Review by timbocode — APPROVED** [review]

**Pull request merged**
